export const routes = {
  PLAY_LANDING: 'Play Home',
  ACTIVITIES_FILTER: 'Activities Filter',
  ACTIVITY_DETAILS: 'Activity Details',
  TOURNAMENT_DETAILS: 'Tournament Details',
  LEAGUE_DETAILS: 'League Details',
  EVENT_DETAILS: 'Event Details',
  PLAYERS_LANDING: 'Players Home',
  PLAYER_PROFILE: 'Player Profile',
  DIRECT_LANDING: 'Direct Home',
  MANAGE_ACTIVITY_DRAWER: 'Manage Activity Drawer',
  MANAGE_ACTIVITY: 'Manage Activity',
  MANAGE_EVENTS: 'Manage Events',
  EVENT_SETTINGS: 'Event Settings',
  ACTIVITY_SETTINGS: 'Activity Settings',
  ME_LANDING: 'Account Home',
  PROFILE: 'Profile',
};
